name: saveur-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - wradlib
  - pandas
  - pytables
  - gdal
  - xarray
  - netCDF4
  - xmltodict
  - arm_pyart
  - cartopy
  - boto3
  - hdf5